'use strict';
function parseCSV(text) {
  text=text.replace(/^\uFEFF/,''); const rows=[];let row=[],cell='',quoted=false,closed=false;
  for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=c;}
  else if(c==='"'){if(cell||closed)throw Error('Unexpected quote in CSV. Use a standard comma-separated export.');quoted=true;}
  else if(c===','||c==='\n'||c==='\r'){row.push(cell.trim());cell='';closed=false;if(c!==','){if(row.some(Boolean))rows.push(row);row=[];if(c==='\r'&&text[i+1]==='\n')i++;}}
  else {if(closed&&c.trim())throw Error('Unexpected text after a quoted CSV value.');if(!closed)cell+=c;}}
  if(quoted)throw Error('CSV contains an unclosed quote.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);
  if(rows.length<2)throw Error('Include a header and at least one data row.');const headers=rows.shift();if(headers.some(x=>!x)||new Set(headers.map(x=>x.toLowerCase())).size!==headers.length)throw Error('Column headers must be nonempty and unique.');
  rows.forEach((r,i)=>{if(r.length!==headers.length)throw Error(`Row ${i+2} has ${r.length} cells; expected ${headers.length}. Quote values containing commas.`);});return {headers,rows};
}
const norm=s=>String(s).trim().replace(/\s+/g,' ').toLowerCase();
function aggregate(data,map,kind){const out=new Map();for(const [i,r] of data.rows.entries()){
 const read=k=>map[k]===undefined||map[k]===''?'':r[Number(map[k])];const campaign=read('campaign'),platform=read('platform');if(!campaign)throw Error(`${kind} row ${i+2}: campaign is empty.`);if(map.platform!==''&&map.platform!==undefined&&!platform)throw Error(`${kind} row ${i+2}: platform is empty.`);
 const obj={campaign,platform};for(const k of (kind==='Spend'?['spend']:['leads','qualified','customers','revenue'])){
 if(k==='revenue'&&(map[k]===''||map[k]===undefined)){obj[k]=null;continue;}const value=read(k);const valid=/^(?:\d+|\d{1,3}(?:,\d{3})+|\d{1,2}(?:,\d{2})*,\d{3})(?:\.\d+)?$/.test(value);const raw=value.replace(/,/g,'');if(!valid)throw Error(`${kind} row ${i+2}: ${k} must be a nonnegative number.`);obj[k]=Number(raw);if(!Number.isFinite(obj[k])||obj[k]>Number.MAX_SAFE_INTEGER)throw Error(`${kind} row ${i+2}: number is too large.`);if(['leads','qualified','customers'].includes(k)&&!Number.isInteger(obj[k]))throw Error(`${kind} row ${i+2}: ${k} must be a whole number.`);}
 if(kind==='CRM'&&(obj.customers>obj.qualified||obj.qualified>obj.leads))throw Error(`CRM row ${i+2}: use customers ≤ qualified leads ≤ leads. Include customers in qualified totals.`);
 const key=JSON.stringify([norm(platform),norm(campaign)]);if(out.has(key)){const old=out.get(key);for(const k of (kind==='Spend'?['spend']:['leads','qualified','customers','revenue']))if(obj[k]!==null){old[k]+=obj[k];if(old[k]>Number.MAX_SAFE_INTEGER)throw Error(`${kind}: total ${k} is too large.`);}}else out.set(key,obj);
 }return out;}
function joinData(spend,crm){return [...new Set([...spend.keys(),...crm.keys()])].map(k=>{const s=spend.get(k),c=crm.get(k);return {...s,...c,spend:s?.spend??null,status:s&&c?'Matched':s?'No CRM match':'No spend match'};});}
function csvCell(value){const text=String(value??'');return '"'+((/^[\s]*[=+@-]/.test(text)||/^[\t\r\n]/.test(text))?"'":'')+text.replace(/"/g,'""')+'"';}
const ratio=(a,b)=>a!==null&&a!==undefined&&b>0?a/b:null;
if(typeof module!=='undefined')module.exports={parseCSV,aggregate,joinData,ratio,csvCell};
if(typeof document!=='undefined'){
 const $=id=>document.getElementById(id);let data={},report=[],demo=false;let generations={spend:0,crm:0};const fields={spend:['campaign','platform','spend'],crm:['campaign','platform','leads','qualified','customers','revenue']};
 const aliases={campaign:['campaign','campaign name','campaign id'],platform:['platform','channel','source'],spend:['spend','amount spent (inr)','amount spent','cost'],leads:['leads','total leads'],qualified:['qualified','qualified leads'],customers:['customers','won','closed won'],revenue:['revenue','customer revenue']};
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function invalidate(){$('export-fallback').hidden=true;$('export-text').value='';report=[];$('results').hidden=true;$('error').textContent='';$('analyze').disabled=!(data.spend&&data.crm);}
 function load(kind,text,name){data[kind]=parseCSV(text);$(''+kind+'-name').textContent=name;$(kind+'-map').innerHTML=fields[kind].map(f=>{const optional=['platform','revenue'].includes(f);let found=data[kind].headers.findIndex(h=>aliases[f].includes(norm(h)));return `<div><label for="${kind}-${f}">${f[0].toUpperCase()+f.slice(1)}${optional?' (optional)':''}</label><select id="${kind}-${f}"><option value="">${optional?'Not provided':'Select column'}</option>${data[kind].headers.map((h,i)=>`<option value="${i}" ${i===found?'selected':''}>${escape(h)}</option>`).join('')}</select></div>`;}).join('');$(kind+'-map').querySelectorAll('select').forEach(el=>el.addEventListener('change',invalidate));invalidate();}
 const spendSample='campaign,platform,spend\nBroad Leads,Meta,30000\nHigh Intent,Google,45000\nLookalike,Meta,25000\nBrand Search,Google,10000\nNew Test,Meta,4000\n';
 const crmSample='campaign,platform,leads,qualified,customers,revenue\nBroad Leads,Meta,300,30,3,18000\nHigh Intent,Google,150,90,18,144000\nLookalike,Meta,200,60,10,70000\nBrand Search,Google,80,56,16,112000\nNew Test,Meta,12,3,0,0\n';
 function download(name,text){const blob=new Blob([text],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.hidden=true;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 function clearInputs(){data={};demo=false;generations.spend++;generations.crm++;for(const k of ['spend','crm']){$(k+'-file').value='';$(k+'-map').innerHTML='';$(k+'-name').textContent='No file selected';}$('period').value='';invalidate();}
 $('sample').onclick=()=>{clearInputs();demo=true;load('spend',spendSample,'Fictional sample · campaign spend');load('crm',crmSample,'Fictional sample · CRM totals');$('period').value='Sample acquisition cohort';analyze();};
 $('spend-template').onclick=()=>download('spend-template.csv',spendSample);$('crm-template').onclick=()=>download('crm-template.csv',crmSample);
 for(const kind of ['spend','crm'])$(kind+'-file').onchange=async e=>{
  const f=e.target.files[0];if(!f)return;
  if(demo)clearInputs();
  demo=false;const generation=++generations[kind];delete data[kind];invalidate();$(kind+'-map').innerHTML='';$(kind+'-name').textContent='Reading '+f.name+'…';
  try{if(f.size>5*1024*1024)throw Error('Use a CSV smaller than 5 MB. Summarise your data by campaign first.');const text=await f.text();if(generation!==generations[kind])return;load(kind,text,f.name);}
  catch(err){if(generation!==generations[kind])return;$(kind+'-name').textContent='File could not be loaded';e.target.value='';$('error').textContent=err.message;}
 };
 function mapping(kind){const m={};for(const f of fields[kind]){m[f]=$(kind+'-'+f).value;if(!['platform','revenue'].includes(f)&&m[f]==='')throw Error(`Select the ${f} column for ${kind}.`);}const chosen=Object.values(m).filter(v=>v!=='');if(new Set(chosen).size!==chosen.length)throw Error(`Each ${kind} column must map to only one field.`);return m;}
 function analyze(){try{$('error').textContent='';const sm=mapping('spend'),cm=mapping('crm');if((sm.platform==='')!==(cm.platform===''))throw Error('Map platform in both files, or omit it in both.');report=joinData(aggregate(data.spend,sm,'Spend'),aggregate(data.crm,cm,'CRM'));render();$('results').focus({preventScroll:true});$('results').scrollIntoView({behavior:'auto',block:'start'});}catch(e){$('results').hidden=true;report=[];$('error').textContent=e.message;}}
 const money=n=>n===null||n===undefined?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:$('currency').value,maximumFractionDigits:0}).format(n);
 const pct=n=>n===null?'—':(n*100).toFixed(1)+'%';
 function render(){$('export-fallback').hidden=true;$('export-text').value='';const matched=report.filter(r=>r.status==='Matched'),sum=k=>{const total=matched.reduce((a,r)=>a+(r[k]??0),0);if(total>Number.MAX_SAFE_INTEGER)throw Error('Combined totals are too large to analyze accurately.');return total;};const spend=sum('spend'),leads=sum('leads'),q=sum('qualified'),customers=sum('customers');const allSpend=report.reduce((a,r)=>a+(r.spend??0),0);$('results').hidden=false;
 $('context').textContent=(demo?'Fictional sample data · ':'')+($('period').value||'Acquisition period not specified')+' · Currency: '+$('currency').value;
 $('coverage').textContent=`${matched.length} of ${report.length} campaign keys matched. ${money(spend)} of ${money(allSpend)} spend included. ${report.length-matched.length} unmatched campaign(s) excluded from overall metrics and rankings. Verify cohort dates and allow time for sales to close.`;
 $('metrics').innerHTML=[['Matched spend',matched.length?money(spend):'—',matched.length?leads+' leads':'No matched data'],['Qualified leads',matched.length?q:'—',pct(ratio(q,leads))+' qualification rate'],['Cost / qualified lead',money(ratio(spend,q)),'Spend ÷ qualified leads'],['Ad cost / customer',money(ratio(spend,customers)),customers+' customers']].map(([title,value,sub])=>`<div class="metric"><small>${title}</small><div class="value">${value}</div><small>${sub}</small></div>`).join('');
 const eligible=matched.filter(r=>r.customers>=5&&r.spend>0).sort((a,b)=>a.spend/a.customers-b.spend/b.customers);const cheap=matched.filter(r=>r.leads>0&&r.spend>0).sort((a,b)=>a.spend/a.leads-b.spend/b.leads)[0];
 const notes=[];if(!matched.length)notes.push(['No matching campaigns','Check campaign names or IDs and platform labels in both files. No combined performance metrics can be calculated until at least one campaign matches.']);if(eligible[0])notes.push(['Lowest observed customer cost',`${eligible[0].campaign}: ${money(eligible[0].spend/eligible[0].customers)} per customer from ${eligible[0].customers} customers. Compared only among campaigns with at least 5 customers; this is a descriptive filter, not statistical confidence.`]);if(cheap)notes.push(['Look beyond the cheapest lead',`${cheap.campaign} has the lowest cost per lead (${money(cheap.spend/cheap.leads)}), with ${pct(ratio(cheap.qualified,cheap.leads))} qualified and ${cheap.customers} customers. Compare sales outcomes before increasing spend.`]);if(matched.length&&!eligible.length)notes.push(['More customer data needed','No matched campaign with positive spend has 5 customers yet. Customer-cost rankings may be unstable.']);
 $('insights').innerHTML=notes.map(([h,t])=>`<div class="insight"><strong>${escape(h)}</strong><p>${escape(t)}</p></div>`).join('');
 const metric=r=>r.status!=='Matched'?null:$('sort').value==='cac'?ratio(r.spend,r.customers):$('sort').value==='cpql'?ratio(r.spend,r.qualified):$('sort').value==='quality'?ratio(r.qualified,r.leads):r.spend;const desc=['quality','spend'].includes($('sort').value);
 const sorted=[...report].sort((a,b)=>{const x=metric(a),y=metric(b);return x===null?(y===null?0:1):y===null?-1:desc?y-x:x-y;});
 $('rows').innerHTML=sorted.map(r=>{const ok=r.status==='Matched',rate=ratio(r.qualified,r.leads);return `<tr><td><strong>${escape(r.campaign)}</strong><small>${escape(r.platform||'Platform not supplied')} · ${escape(r.status)}${ok&&r.customers<5?' · Few customers':''}</small></td><td>${money(r.spend)}</td><td>${r.leads??'—'}</td><td>${r.qualified??'—'}</td><td>${r.customers??'—'}</td><td>${pct(rate)}${rate!==null?`<div class="bar"><span style="width:${rate*100}%"></span></div>`:''}</td><td>${ok?money(ratio(r.spend,r.leads)):'—'}</td><td>${ok?money(ratio(r.spend,r.qualified)):'—'}</td><td>${ok?money(ratio(r.spend,r.customers)):'—'}</td><td>${ok&&r.revenue!==null&&r.spend>0?(r.revenue/r.spend).toFixed(2)+'×':'—'}</td></tr>`;}).join('');}
 $('analyze').onclick=analyze;$('sort').onchange=()=>{if(report.length)render();};$('currency').onchange=()=>{if(report.length)render();};$('period').oninput=()=>{if(report.length)render();};$('print').onclick=()=>window.print();
 $('reset').onclick=clearInputs;
 $('export').onclick=()=>{const safe=csvCell;const rows=[['data_type','cohort','currency','campaign','platform','match_status','spend','leads','qualified','customers','quality_rate','cost_per_lead','cost_per_qualified','ad_cost_per_customer','revenue','revenue_per_spend']];for(const r of report){const ok=r.status==='Matched';rows.push([demo?'Fictional sample':'Imported data',$('period').value,$('currency').value,r.campaign,r.platform,r.status,r.spend,r.leads,r.qualified,r.customers,ratio(r.qualified,r.leads),ok?ratio(r.spend,r.leads):null,ok?ratio(r.spend,r.qualified):null,ok?ratio(r.spend,r.customers):null,r.revenue,ok?ratio(r.revenue,r.spend):null]);}const csv=rows.map(r=>r.map(safe).join(',')).join('\r\n');$('export-text').value=csv;$('export-fallback').hidden=false;$('export-fallback').open=true;download('lead-quality-report.csv',csv);};
}
